FROM registry.access.redhat.com/ubi8/nodejs-14 AS appbuild

LABEL version="1.0" \
      description="To Do List application builder"

USER 0

# ENV REACT_APP_API_HOST=http://localhost:3000
ENV REACT_APP_API_HOST=""

COPY . /tmp/todo-frontend

RUN cd /tmp/todo-frontend && \
    npm install && \
    npm run build

# https://github.com/sclorg/nginx-container
FROM registry.access.redhat.com/ubi8/nginx-118

LABEL version="1.0" \
      description="To Do List application builder" \
      io.k8s.description="DESC" \
      io.k8s.display-name="NAME" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="todolist, node, nginx" 

COPY nginx.conf /etc/nginx/
COPY --from=appbuild /tmp/todo-frontend/build /usr/share/nginx/html

EXPOSE 8080
USER nginx
CMD nginx -g "daemon off;"
